// Winterfell Wares and Goods
#define WINTERFELL_SWEET_BEET 190
#define WINTERFELL_TIMBER 220
#define WINTERFELL_INTRICATE_LACE 385
#define WINTERFELL_INTOXICATING_PERFUME 489
#define WINTERFELL_PALE_AMBER_WINE 599
#define WINTERFELL_MYRISH_EYE 695
#define WINTERFELL_QOHORIK_TAPESTRY 780
#define WINTERFELL_VALYRIAN_STEEL 898

// Lys Wares and Goods
#define LYS_SWEET_BEET 189
#define LYS_TIMBER 295
#define LYS_INTRICATE_LACE 399
#define LYS_INTOXICATING_PERFUME 432
#define LYS_PALE_AMBER_WINE 586
#define LYS_MYRISH_EYE 699
#define LYS_QOHORIK_TAPESTRY 789
#define LYS_VALYRIAN_STEEL 885

// Myr Wares and Goods
#define MYR_SWEET_BEET 199
#define MYR_TIMBER 297
#define MYR_INTRICATE_LACE 321
#define MYR_INTOXICATING_PERFUME 486
#define MYR_PALE_AMBER_WINE 595
#define MYR_MYRISH_EYE 647
#define MYR_QOHORIK_TAPESTRY 797
#define MYR_VALYRIAN_STEEL 883

// Pentos Wares and Goods
#define PENTOS_SWEET_BEET 198
#define PENTOS_TIMBER 300
#define PENTOS_INTRICATE_LACE 380
#define PENTOS_INTOXICATING_PERFUME 496
#define PENTOS_PALE_AMBER_WINE 543
#define PENTOS_MYRISH_EYE 698
#define PENTOS_QOHORIK_TAPESTRY 800
#define PENTOS_VALYRIAN_STEEL 880

// Qohor Wares and Goods
#define QOHOR_SWEET_BEET 180
#define QOHOR_TIMBER 300
#define QOHOR_INTRICATE_LACE 398
#define QOHOR_INTOXICATING_PERFUME 481
#define QOHOR_PALE_AMBER_WINE 582
#define QOHOR_MYRISH_EYE 683
#define QOHOR_QOHORIK_TAPESTRY 750
#define QOHOR_VALYRIAN_STEEL 800

// Volantis Wares and Goods
#define VOLANTIS_SWEET_BEET 100
#define VOLANTIS_TIMBER 284
#define VOLANTIS_INTRICATE_LACE 383
#define VOLANTIS_INTOXICATING_PERFUME 482
#define VOLANTIS_PALE_AMBER_WINE 581
#define VOLANTIS_MYRISH_EYE 694
#define VOLANTIS_QOHORIK_TAPESTRY 793
#define VOLANTIS_VALYRIAN_STEEL 888